# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"never": "tyrion.ipynb"}

modules = ["ever.py"]

doc_url = "https://d-genk.github.io/nodocs/"

git_url = "https://github.com/d-genk/nodocs/tree/master/"

def custom_doc_links(name): return None
